# -*- coding: utf-8 -*-
"""Question 12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P33EIaVz4SaASBtWDwL5c4sG1Sj1jcKz

Stage (t): Each machine, t = 1, 2, 3, 4

State (s): The set of jobs still available to be assigned at stage t

Action (x): Which job to assign to machine t from the remaining available jobs

State Transition:

s(t+1) = s(t) − {x(t)} (remove assigned job from available set)

Contribution Function:

C(t, x) = setup_time[machine t][job x]

DP Recursion (minimization):

f(t, s) = min over x∈s { cost(t, x) + f(t+1, s − {x}) }

Terminal Condition:

f(5, {}) = 0
"""

import pandas as pd
from itertools import permutations

# ── Problem Parameters ───────────────────────────────────────────────────────
# cost[machine][job] — both 0-indexed internally
cost = {
    1: {1: 14, 2:  5, 3: 8, 4:  7},
    2: {1:  2, 2: 12, 3: 6, 4:  5},
    3: {1:  7, 2:  8, 3: 3, 4:  9},
    4: {1:  2, 2:  4, 3: 6, 4: 10},
}

machines = [1, 2, 3, 4]
jobs     = [1, 2, 3, 4]

# ── DP using bitmask to represent set of remaining jobs ──────────────────────
# bitmask: bit j-1 set means job j is still available
# e.g. 0b1111 = 15 means all 4 jobs available

def jobs_in_mask(mask):
    return [j for j in jobs if mask & (1 << (j - 1))]

def remove_job(mask, j):
    return mask & ~(1 << (j - 1))

INF   = float('inf')
n     = len(machines)

# f[t][mask]    = min cost from machine t onwards with jobs in mask available
# x_opt[t][mask] = optimal job to assign to machine t given mask

f     = [[INF] * (1 << n) for _ in range(n + 2)]
x_opt = [[None] * (1 << n) for _ in range(n + 2)]

# Terminal condition: no machines left, no cost
for mask in range(1 << n):
    f[n + 1][mask] = 0

# Backward Induction
for t in range(n, 0, -1):
    for mask in range(1 << n):
        available = jobs_in_mask(mask)
        if not available:
            f[t][mask] = 0
            continue

        best_cost = INF
        best_job  = None

        for j in available:
            next_mask  = remove_job(mask, j)
            future     = f[t + 1][next_mask]
            total      = cost[t][j] + future

            if total < best_cost:
                best_cost = total
                best_job  = j

        f[t][mask]     = best_cost
        x_opt[t][mask] = best_job

# ── Trace optimal assignment
full_mask  = (1 << n) - 1   # all jobs available = 0b1111 = 15
assignment = {}
mask       = full_mask

for t in range(1, n + 1):
    j             = x_opt[t][mask]
    assignment[t] = j
    mask          = remove_job(mask, j)

# Print cost matrix
print("=" * 60)
print("  ASSIGNMENT PROBLEM — MINIMIZE SETUP TIME")
print("=" * 60)
print("\n  Cost Matrix (Setup Time):")
df_cost = pd.DataFrame(cost).T
df_cost.index.name   = "Machine"
df_cost.columns.name = "Job"
print(df_cost.to_string())

# Print DP table
print("\n")
print("  DP Table  f(machine, available_jobs) = min cost from machine t:")
print(f"  {'─'*55}")
rows = []
for t in range(1, n + 1):
    for mask in range(1, 1 << n):
        available = jobs_in_mask(mask)
        if len(available) == n - t + 1:   # only show relevant states
            rows.append({
                "Machine (t)"     : t,
                "Jobs Available"  : str(available),
                "f(t, mask)"      : f[t][mask],
                "Optimal Job x"   : x_opt[t][mask]
            })
df_dp = pd.DataFrame(rows)
print(df_dp.to_string(index=False))

# Print optimal assignment
print("=" * 60)
print("  OPTIMAL ASSIGNMENT")
print("=" * 60)
total = 0
for t in range(1, n + 1):
    j    = assignment[t]
    c    = cost[t][j]
    total += c
    print(f"  Machine {t}  →  Job {j}   (setup time = {c})")
print(f"  {'─'*40}")
print(f"  TOTAL MINIMUM SETUP TIME = {total}")
print("=" * 60)

# Verify by brute force
print("\n  Verification — All permutations:")
best_perm = None
best_val  = INF
perm_rows = []
for perm in permutations(jobs):
    total_perm = sum(cost[m][j] for m, j in zip(machines, perm))
    perm_rows.append({
        "Assignment (M1,M2,M3,M4)": perm,
        "Total Setup Time"        : total_perm,
        "Optimal?"                : "✓" if total_perm == f[1][full_mask] else ""
    })
    if total_perm < best_val:
        best_val  = total_perm
        best_perm = perm

df_perm = pd.DataFrame(perm_rows).sort_values("Total Setup Time")
print(df_perm.to_string(index=False))
print(f"\n  Brute force minimum: {best_val}  →  {best_perm}")
print(f"  DP minimum        : {f[1][full_mask]}")
print(f"  Match: {best_val == f[1][full_mask]}")

